project_id = "rzgsqaasexjjqajfwkdu"

[functions.run-icp]
verify_jwt = false

[functions.check-run]
verify_jwt = false

[functions.export-leads]
verify_jwt = false

[functions.run-automations]
verify_jwt = false

[functions.webhook-cnpj]
verify_jwt = false

[functions.enrich-leads]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.webhook-cakto]
verify_jwt = false

[functions.stripe-financial]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
